#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 5424026
#
Name     : xfce4-screensaver
Version  : 4.18.4
Release  : 10
URL      : https://archive.xfce.org/src/apps/xfce4-screensaver/4.18/xfce4-screensaver-4.18.4.tar.bz2
Source0  : https://archive.xfce.org/src/apps/xfce4-screensaver/4.18/xfce4-screensaver-4.18.4.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0 LGPL-2.1
Requires: xfce4-screensaver-bin = %{version}-%{release}
Requires: xfce4-screensaver-data = %{version}-%{release}
Requires: xfce4-screensaver-libexec = %{version}-%{release}
Requires: xfce4-screensaver-license = %{version}-%{release}
Requires: xfce4-screensaver-locales = %{version}-%{release}
Requires: xfce4-screensaver-man = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : buildreq-configure
BuildRequires : gettext
BuildRequires : glibc-staticdev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(garcon-gtk3-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libwnck-3.0)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(libxklavier)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xscrnsaver)
BuildRequires : xmlto
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![License](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://gitlab.xfce.org/apps/xfce4-screensaver/-/blob/master/COPYING)

%package bin
Summary: bin components for the xfce4-screensaver package.
Group: Binaries
Requires: xfce4-screensaver-data = %{version}-%{release}
Requires: xfce4-screensaver-libexec = %{version}-%{release}
Requires: xfce4-screensaver-license = %{version}-%{release}

%description bin
bin components for the xfce4-screensaver package.


%package data
Summary: data components for the xfce4-screensaver package.
Group: Data

%description data
data components for the xfce4-screensaver package.


%package libexec
Summary: libexec components for the xfce4-screensaver package.
Group: Default
Requires: xfce4-screensaver-license = %{version}-%{release}

%description libexec
libexec components for the xfce4-screensaver package.


%package license
Summary: license components for the xfce4-screensaver package.
Group: Default

%description license
license components for the xfce4-screensaver package.


%package locales
Summary: locales components for the xfce4-screensaver package.
Group: Default

%description locales
locales components for the xfce4-screensaver package.


%package man
Summary: man components for the xfce4-screensaver package.
Group: Default

%description man
man components for the xfce4-screensaver package.


%prep
%setup -q -n xfce4-screensaver-4.18.4
cd %{_builddir}/xfce4-screensaver-4.18.4
pushd ..
cp -a xfce4-screensaver-4.18.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735119066
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735119066
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfce4-screensaver
cp %{_builddir}/xfce4-screensaver-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xfce4-screensaver/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/xfce4-screensaver-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/xfce4-screensaver/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/xfce4-screensaver-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/xfce4-screensaver/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang xfce4-screensaver
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/xfce4-screensaver
/V3/usr/bin/xfce4-screensaver-command
/V3/usr/bin/xfce4-screensaver-preferences
/usr/bin/xfce4-screensaver
/usr/bin/xfce4-screensaver-command
/usr/bin/xfce4-screensaver-configure.py
/usr/bin/xfce4-screensaver-preferences

%files data
%defattr(-,root,root,-)
/usr/share/applications/screensavers/xfce-floaters.desktop
/usr/share/applications/screensavers/xfce-personal-slideshow.desktop
/usr/share/applications/screensavers/xfce-popsquares.desktop
/usr/share/applications/xfce4-screensaver-preferences.desktop
/usr/share/dbus-1/services/org.xfce.ScreenSaver.service
/usr/share/desktop-directories/xfce4-screensaver.directory
/usr/share/icons/hicolor/128x128/apps/org.xfce.ScreenSaver.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.ScreenSaver.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.ScreenSaver.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.ScreenSaver.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.ScreenSaver.png
/usr/share/icons/hicolor/scalable/apps/org.xfce.ScreenSaver.svg
/usr/share/pixmaps/xfce-logo-white.svg

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/xfce4-screensaver-dialog
/V3/usr/libexec/xfce4-screensaver-gl-helper
/V3/usr/libexec/xfce4-screensaver/floaters
/V3/usr/libexec/xfce4-screensaver/popsquares
/V3/usr/libexec/xfce4-screensaver/slideshow
/usr/libexec/xfce4-screensaver-dialog
/usr/libexec/xfce4-screensaver-gl-helper
/usr/libexec/xfce4-screensaver/floaters
/usr/libexec/xfce4-screensaver/popsquares
/usr/libexec/xfce4-screensaver/slideshow

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfce4-screensaver/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/xfce4-screensaver/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/xfce4-screensaver/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xfce4-screensaver-command.1
/usr/share/man/man1/xfce4-screensaver-preferences.1
/usr/share/man/man1/xfce4-screensaver.1

%files locales -f xfce4-screensaver.lang
%defattr(-,root,root,-)

