#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-screensaver
Version  : 0.1.9
Release  : 2
URL      : https://archive.xfce.org/src/apps/xfce4-screensaver/0.1/xfce4-screensaver-0.1.9.tar.bz2
Source0  : https://archive.xfce.org/src/apps/xfce4-screensaver/0.1/xfce4-screensaver-0.1.9.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0 LGPL-2.1
Requires: xfce4-screensaver-bin = %{version}-%{release}
Requires: xfce4-screensaver-data = %{version}-%{release}
Requires: xfce4-screensaver-libexec = %{version}-%{release}
Requires: xfce4-screensaver-license = %{version}-%{release}
Requires: xfce4-screensaver-locales = %{version}-%{release}
Requires: xfce4-screensaver-man = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : gettext
BuildRequires : glibc-staticdev
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(garcon-gtk3-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libwnck-3.0)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(libxklavier)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xscrnsaver)
BuildRequires : xmlto

%description
Xfce Screensaver
================
xfce4-screensaver is a screen saver and locker that aims to have
simple, sane, secure defaults and be well integrated with the desktop.

%package bin
Summary: bin components for the xfce4-screensaver package.
Group: Binaries
Requires: xfce4-screensaver-data = %{version}-%{release}
Requires: xfce4-screensaver-libexec = %{version}-%{release}
Requires: xfce4-screensaver-license = %{version}-%{release}

%description bin
bin components for the xfce4-screensaver package.


%package data
Summary: data components for the xfce4-screensaver package.
Group: Data

%description data
data components for the xfce4-screensaver package.


%package libexec
Summary: libexec components for the xfce4-screensaver package.
Group: Default
Requires: xfce4-screensaver-license = %{version}-%{release}

%description libexec
libexec components for the xfce4-screensaver package.


%package license
Summary: license components for the xfce4-screensaver package.
Group: Default

%description license
license components for the xfce4-screensaver package.


%package locales
Summary: locales components for the xfce4-screensaver package.
Group: Default

%description locales
locales components for the xfce4-screensaver package.


%package man
Summary: man components for the xfce4-screensaver package.
Group: Default

%description man
man components for the xfce4-screensaver package.


%prep
%setup -q -n xfce4-screensaver-0.1.9
cd %{_builddir}/xfce4-screensaver-0.1.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588489131
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1588489131
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfce4-screensaver
cp %{_builddir}/xfce4-screensaver-0.1.9/COPYING %{buildroot}/usr/share/package-licenses/xfce4-screensaver/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/xfce4-screensaver-0.1.9/COPYING.LGPL %{buildroot}/usr/share/package-licenses/xfce4-screensaver/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/xfce4-screensaver-0.1.9/COPYING.LIB %{buildroot}/usr/share/package-licenses/xfce4-screensaver/ba8966e2473a9969bdcab3dc82274c817cfd98a1
%make_install
%find_lang xfce4-screensaver

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xfce4-screensaver
/usr/bin/xfce4-screensaver-command
/usr/bin/xfce4-screensaver-configure
/usr/bin/xfce4-screensaver-preferences

%files data
%defattr(-,root,root,-)
/usr/share/applications/screensavers/xfce-floaters.desktop
/usr/share/applications/screensavers/xfce-personal-slideshow.desktop
/usr/share/applications/screensavers/xfce-popsquares.desktop
/usr/share/applications/xfce4-screensaver-preferences.desktop
/usr/share/dbus-1/services/org.xfce.ScreenSaver.service
/usr/share/desktop-directories/xfce4-screensaver.directory
/usr/share/pixmaps/xfce-logo-white.svg

%files libexec
%defattr(-,root,root,-)
/usr/libexec/xfce4-screensaver-dialog
/usr/libexec/xfce4-screensaver-gl-helper
/usr/libexec/xfce4-screensaver/floaters
/usr/libexec/xfce4-screensaver/popsquares
/usr/libexec/xfce4-screensaver/slideshow

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfce4-screensaver/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/xfce4-screensaver/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/xfce4-screensaver/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xfce4-screensaver-command.1
/usr/share/man/man1/xfce4-screensaver-preferences.1
/usr/share/man/man1/xfce4-screensaver.1

%files locales -f xfce4-screensaver.lang
%defattr(-,root,root,-)

